Repository knative/eventing-operator, pull requests merged in 2019-11, with the labels that each got.

#27 Add the marker of the latest commit ID for better debugging
  test/e2e-tests-latest-eventing.sh
Labels: approved, lgtm, size/XS

#34 Adding matzew as approver
  OWNERS
Labels: approved, lgtm, size/XS

#33 Fixing invalid name for metrics component
  cmd/manager/main.go
  config/operator.yaml
Labels: approved, lgtm, size/S

#36 golang format tools
  pkg/apis/eventing/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/knativeeventing_types.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/reconciler.go
  test/e2e/knativeeventingdeployment_test.go
Labels: approved, lgtm, size/S

#30 State prerequisites in README.md explicitly
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#37 Format markdown
  README.md
Labels: approved, lgtm, size/XS

#41 Format markdown
  README.md
Labels: approved, lgtm, size/XS

#42 Add version consistency test
  version/version.go
  version/version_test.go
Labels: approved, lgtm, ok-to-test, size/M

#44 golang format tools
  version/version_test.go
Labels: approved, lgtm, size/XS
