Repository knative/eventing-operator, pull requests merged in 2019-10, with the labels that each got.

#12 Adding IMC
  cmd/manager/kodata/knative-eventing/0.9.0-imc.yaml
Labels: approved, lgtm, size/L

#14 Move the CRDs under the directory config
  README.md
  config/300-eventing-v1alpha1-knativeeventing-crd.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#16 Update the license of third party and symlinking to licenses
  cmd/manager/kodata/HEAD
  cmd/manager/kodata/LICENSE
  cmd/manager/kodata/VENDOR-LICENSE
  cmd/manager/kodata/refs
  hack/update-deps.sh
  third_party/VENDOR-LICENSE
Labels: approved, lgtm, size/XXL

#19 latest release
  cmd/manager/kodata/knative-eventing/0.10.0-imc.yaml
  cmd/manager/kodata/knative-eventing/0.10.0.yaml
Labels: approved, lgtm, size/XL

#21 Letting flags be changed from outside
  .gitignore
  test/e2e_flags.go
Labels: approved, lgtm, ok-to-test, size/S

#22 Adding version update
  version/version.go
Labels: approved, lgtm, size/XS

#24 Add the test against the latest generated manifest of eventing
  test/e2e-tests-latest-eventing.sh
Labels: approved, lgtm, size/L

#25 Fix the nightly build issue of prow job
  hack/generate-yamls.sh
Labels: approved, lgtm, size/XS
