Repository knative/eventing-operator, pull requests merged in 2020-02, with the labels that each got.

#85 OLM metadata for 0.12.0
  README.md
  deploy/olm-catalog/knative-eventing-operator/0.11.0/eventing-v1alpha1-knativeeventing-crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.12.0/eventing-v1alpha1-knativeeventing-crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.12.0/eventing-v1alpha1-knativeeventing-obsolete-crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.12.0/knative-eventing-operator.v0.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-eventing-operator/knative-eventing-operator.package.yaml
  hack/generate-olm-catalog-source.sh
Labels: approved, lgtm, ok-to-test, size/L

#95 Remove obsolete resources caused by merging controllers
  cmd/manager/kodata/knative-eventing/v20200206-05bba2be.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
  version/version.go
Labels: approved, lgtm, ok-to-test, size/XL

#96 Rename the test file into e2e-upgrade-tests.sh for upgrade
  test/e2e-upgrade-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#100 Read Kubeconfig from env var if previous methods don't work
  pkg/reconciler/knativeeventing/controller.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#103 golang format tools
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, lgtm, size/XS

#105 Build config consistently as per in serving
  cmd/manager/main.go
  pkg/reconciler/knativeeventing/controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#93 Add upgrade tests into the e2e-tests-latest-eventing
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/client/setup.go
  test/e2e-upgrade-tests.sh
  test/e2e/knativeeventingdeployment_test.go
  test/resources/knativeeventing.go
  test/resources/verify.go
  test/upgrade/knativeeventingupgrade_test.go
Labels: approved, lgtm, size/L

#98 Add additionalPrinterColumns
  config/300-eventing-v1alpha1-knativeeventing-crd.yaml
Labels: approved, lgtm, size/S

#108 golang format tools
  pkg/reconciler/knativeeventing/common/extensions_test.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/resources/knativeeventing.go
  test/resources/verify.go
  test/upgrade/knativeeventingupgrade_test.go
Labels: approved, lgtm, size/M

#113 No CRD deletes
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/resources/verify.go
  third_party/VENDOR-LICENSE
  vendor/github.com/go-logr/logr/testing/null.go
  vendor/github.com/go-logr/logr/testing/test.go
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/github.com/manifestival/client-go-client/LICENSE
  vendor/github.com/manifestival/client-go-client/client.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/options.go
  vendor/github.com/manifestival/manifestival/source.go
  vendor/github.com/manifestival/manifestival/sources/path.go
  vendor/github.com/manifestival/manifestival/sources/yaml.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
  version/version_test.go
Labels: approved, lgtm, size/XXL

#115 Keep the sources-controller, since 0.12 still has it
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/e2e-upgrade-tests.sh
  test/upgrade/knativeeventingupgrade_test.go
Labels: approved, lgtm, release-0.12, size/M
