Repository knative/eventing-operator, pull requests merged in 2020-04, with the labels that each got.

#172 Use finalizers to block CR deletion until all resources are deleted
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/resources/verify.go
Labels: approved, cla: yes, lgtm, size/M

#174 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: cla: yes, size/XS

#173 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/performance/performance.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: cla: yes, size/L

#167 Override images in env vars (#152)
  pkg/reconciler/knativeeventing/common/images.go
  pkg/reconciler/knativeeventing/common/images_test.go
Labels: approved, cla: no, size/L

#176 Add aliok as one approver of knative operator
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#179 Update manifestival to 0.4.0
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/resources/verify.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/patch/patch.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#180 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/L

#185 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/XXL

#188 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#186 Reconciliation for default broker selection
  Gopkg.lock
  Gopkg.toml
  cmd/manager/kodata/knative-eventing/eventing.yaml
  config/300-eventing-v1alpha1-knativeeventing-crd.yaml
  pkg/apis/eventing/v1alpha1/knativeeventing_types.go
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  pkg/reconciler/knativeeventing/common/extensions.go
  pkg/reconciler/knativeeventing/common/extensions_test.go
  test/upgrade/knativeeventingupgrade_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing/AUTHORS
  vendor/knative.dev/eventing/LICENSE
  vendor/knative.dev/eventing/cmd/apiserver_receive_adapter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/broker/filter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/broker/ingress/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/channel_broker/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/in_memory/channel_controller/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/in_memory/channel_dispatcher/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/filter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/mtbroker/ingress/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/adapter/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/ping/jobrunner/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/pong/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/sendevent/kodata/LICENSE
  vendor/knative.dev/eventing/cmd/webhook/kodata/LICENSE
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/doc.go
  vendor/knative.dev/eventing/pkg/apis/config/store.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  version/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#190 Update the manifest of eventing to release 14
  Gopkg.lock
  Gopkg.toml
  cmd/manager/kodata/knative-eventing/0.14.0.yaml
  pkg/reconciler/knativeeventing/common/extensions_test.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#191 Add update to the apigroup autoscaling
  config/role.yaml
Labels: approved, cla: yes, lgtm, size/XS

#192 Adding doc to change the actual broker
  README.md
Labels: approved, cla: yes, lgtm, size/S

#193 Add the apigroup batch into the cluster role for 0.14
  cmd/manager/kodata/knative-eventing/1-eventing.yaml
  cmd/manager/kodata/knative-eventing/2-upgrade-to-v0.14.0.yaml
  config/role.yaml
Labels: approved, cla: yes, lgtm, size/S

#197 Add support of configuring ConfigMaps with CR
  config/300-eventing-v1alpha1-knativeeventing-crd.yaml
  pkg/apis/eventing/v1alpha1/knativeeventing_types.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeeventing/common/config_maps.go
  pkg/reconciler/knativeeventing/common/config_maps_test.go
  pkg/reconciler/knativeeventing/common/extensions.go
  pkg/reconciler/knativeeventing/common/extensions_test.go
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, size/L

#195 [master] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#198 Add support of configuring ConfigMaps with CR (#197)
  config/300-eventing-v1alpha1-knativeeventing-crd.yaml
  pkg/apis/eventing/v1alpha1/knativeeventing_types.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeeventing/common/config_maps.go
  pkg/reconciler/knativeeventing/common/config_maps_test.go
  pkg/reconciler/knativeeventing/common/extensions.go
  pkg/reconciler/knativeeventing/common/extensions_test.go
  test/e2e-upgrade-tests.sh
Labels: approved, cla: no, size/L

#200 Change the name from defaultBrokerClass to default-broker-class
  config/300-eventing-v1alpha1-knativeeventing-crd.yaml
  pkg/apis/eventing/v1alpha1/knativeeventing_types.go
Labels: approved, cla: yes, lgtm, size/XS

#201 forgotten rename.... :lipstick:
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#204 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#202 Pass config from main to the controller.
  cmd/manager/main.go
  pkg/reconciler/knativeeventing/controller.go
Labels: approved, cla: yes, lgtm, size/M

#206 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#207 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M
