Repository knative/eventing-operator, pull requests merged in 2020-01, with the labels that each got.

#50 Adding Travis CI build
  .travis.yml
Labels: approved, lgtm, ok-to-test, size/M

#69 Have OLM metadata in source repo for reference
  deploy/olm-catalog/knative-eventing-operator/0.11.0/eventing_v1alpha1_knativeeventing_crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.11.0/knative-eventing-operator.v0.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-eventing-operator/knative-eventing-operator.package.yaml
Labels: approved, lgtm, ok-to-test, size/L

#72 Update the year of copyright to 2020 in the template
  hack/boilerplate/boilerplate.go.txt
Labels: approved, lgtm, size/XS

#73 Add the standard templates as Knative projects
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, lgtm, size/M

#78 Fix spelling errors
  pkg/reconciler/knativeeventing/knativeeventingobsolete.go
Labels: approved, lgtm, size/XS

#79 golang format tools
  pkg/reconciler/knativeeventing/controllerobsolete.go
  pkg/reconciler/knativeeventing/knativeeventingobsolete.go
Labels: approved, lgtm, size/S

#82 Add the badges into the README.md
  README.md
Labels: approved, lgtm, size/XS

#80 Add the guidance on upgrade
  README.md
  doc/upgrade_guide.md
Labels: approved, lgtm, size/M

#87 Format markdown
  README.md
  doc/upgrade_guide.md
Labels: approved, lgtm, size/M

#86 Gitignore some files
  .gitignore
Labels: approved, lgtm, ok-to-test, size/M

#89 Remove old .travis.yml file
  .travis.yml
Labels: approved, lgtm, size/M
