Repository knative/eventing-operator, pull requests merged in 2020-03, with the labels that each got.

#118 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, lgtm, size/S

#119 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/S

#117 OLM metadata for 0.12.1
  deploy/olm-catalog/knative-eventing-operator/0.12.1/eventings.operator.knative.dev.obsolete.crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.12.1/knative-eventing-operator.v0.12.1.clusterserviceversion.yaml
  deploy/olm-catalog/knative-eventing-operator/0.12.1/knativeeventings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-eventing-operator/knative-eventing-operator.package.yaml
Labels: approved, lgtm, size/L

#122 Removing myself from approvers
  OWNERS
Labels: approved, lgtm, size/XS

#127 Log all the information in manifestival library
  Gopkg.lock
  pkg/reconciler/knativeeventing/controller.go
  third_party/VENDOR-LICENSE
  vendor/github.com/go-logr/zapr/LICENSE
  vendor/github.com/go-logr/zapr/zapr.go
Labels: approved, lgtm, size/XL

#125 Use ko's strict mode for better errors messages
  config/operator.yaml
  hack/generate-yamls.sh
Labels: approved, lgtm, size/XS

#133 Remove obsolete controller
  cmd/manager/main.go
  config/300-eventing-v1alpha1-knativeeventing-crd-obsolete.yaml
  pkg/apis/eventing/v1alpha1/knativeeventing_types_obsolete.go
  pkg/apis/eventing/v1alpha1/register.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/eventing/v1alpha1/eventing.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/injection/informers/eventing/v1alpha1/eventing/eventing.go
  pkg/client/injection/informers/eventing/v1alpha1/eventing/fake/fake.go
  pkg/client/listers/eventing/v1alpha1/eventing.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  pkg/reconciler/knativeeventing/controllerobsolete.go
  pkg/reconciler/knativeeventing/knativeeventingobsolete.go
Labels: approved, lgtm, size/L

#132 Update the manifest to version 0.13.3
  cmd/manager/kodata/knative-eventing/0.13.3.yaml
  version/version.go
Labels: approved, lgtm, size/L

#134 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, do-not-merge/hold, lgtm, size/S

#139 [release-0.13]Update test-infra for release hotfix
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, size/S

#138 Update test-infra for release hotfix
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, size/S

#142 Update manifestival to 0.4.0
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/resources/verify.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/patch/patch.go
  vendor/github.com/manifestival/manifestival/transform.go
Labels: approved, cla: yes, lgtm, size/L

#141 Delete (Cluster)Role(Bindings) as a final cleanup step.
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, cla: yes, lgtm, size/S

#144 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#145 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#146 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#109 Restrict RBAC for Operator
  config/role.yaml
  config/role_binding.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, cla: yes, lgtm, size/L

#154 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#151 Add Cynocracy to reviewers.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#153 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#152 Override images in env vars
  pkg/reconciler/knativeeventing/common/images.go
  pkg/reconciler/knativeeventing/common/images_test.go
Labels: approved, cla: yes, lgtm, size/L

#149 k4leung4 steps down as approver/reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#155 Update the manifest of eventing into 0.13.4
  cmd/manager/kodata/knative-eventing/0.13.4.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#131 Remove the obsolete resource in 0.13
  cmd/manager/kodata/knative-eventing/eventing.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/e2e-upgrade-tests.sh
  version/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#159 Avoid name conflict by using deployment+delimiter+container as the key
  pkg/reconciler/knativeeventing/common/images.go
  pkg/reconciler/knativeeventing/common/images_test.go
Labels: approved, cla: yes, lgtm, size/L

#161 Avoid name conflict by using deployment+delimiter+container as the key (#159)
  pkg/reconciler/knativeeventing/common/images.go
  pkg/reconciler/knativeeventing/common/images_test.go
Labels: approved, cla: yes, size/M

#165 Update to 0.13.5
  cmd/manager/kodata/knative-eventing/0.13.5.yaml
  version/version.go
Labels: approved, cla: yes, size/L

#164 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: cla: yes, size/L

#163 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: cla: yes, size/XS
